# Generated by Django 4.0.3 on 2022-04-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latin', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('habitat', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('collector', models.CharField(max_length=150)),
                ('determinate', models.CharField(max_length=150)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='img', to='herbarium.plantimage')),
            ],
        ),
    ]
